Scripts prefix log lines with their `basename`.
Also added some new output, a new terminal colour.

diff --git a/common b/common
--- a/common
+++ b/common
@@ -27,47 +27,55 @@ readonly CONFIGURATION_CLASS_NAME='Configuration.kt'
 
 # Terminal Output
 if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
-    COLOR_RESET='[0m'; COLOR_RED='[31m'; COLOR_GREEN='[32m'; COLOR_BLUE='[34m'
+    COLOR_RESET='[0m'; COLOR_RED='[31m'; COLOR_GREEN='[32m'; COLOR_YELLOW='[33m'; COLOR_BLUE='[34m'
 else
-    COLOR_RESET=''; COLOR_RED=''; COLOR_GREEN=''; COLOR_BLUE=''
+    COLOR_RESET=''; COLOR_RED=''; COLOR_GREEN=''; COLOR_YELLOW=''; COLOR_BLUE=''
 fi
 
 function sQuote { echo "'${1}'" ; }
 function red { echo "${COLOR_RED}${1}${COLOR_RESET}" ; }
-function blue { echo "${COLOR_BLUE}${1}${COLOR_RESET}" ; }
 function green { echo "${COLOR_GREEN}${1}${COLOR_RESET}" ; }
-function logInfo  { echo -e "$(blue "$(TZ=${TIME_ZONE} date +${DATE_FORMAT})")" "$(green "INFO") ${1}" ; }
-function logError { echo -e "$(blue "$(TZ=${TIME_ZONE} date +${DATE_FORMAT})")" "$(red   "ERROR") ${1}" ; }
+function yellow { echo "${COLOR_YELLOW}${1}${COLOR_RESET}" ; }
+function blue { echo "${COLOR_BLUE}${1}${COLOR_RESET}" ; }
+function logInfo  { echo -e "$(blue "$(TZ=${TIME_ZONE} date +${DATE_FORMAT})")" "$(yellow "$1")" "$(green "INFO")" "${2}" ; }
+function logError  { echo -e "$(blue "$(TZ=${TIME_ZONE} date +${DATE_FORMAT})")" "$(red "$1")" "$(green "INFO")" "${2}" ; }
+
 
 #    Fetches a URL until a given status code is returned. Up to a specified number attempts and with a configurable
 #    sleep between each request.
 #
-#   #1 = the name of the site
-#   #2 = the URL to get
-#   #3 = the expected success HTTP status code
-#   #4 = the maximum number of attempts
-#   #5 = the 'sleep' argument to use between fetches
+#   #1 = the name of the calling script
+#   #2 = the name of the site
+#   #3 = the URL to get
+#   #4 = the expected success HTTP status code
+#   #5 = the maximum number of attempts
+#   #6 = the 'sleep' argument to use between fetches
 function waitForStatusCode {
-  logInfo "Waiting for $(green "${1}") ($(green "${2}")) to return $(blue "${3}")..."
+  logInfo "${1}" "Waiting for $(green "${2}") ($(green "${3}")) to return $(blue "${4}")..."
   local statusCode
   # shellcheck disable=SC2034
-  for attempt in $(seq 1 "${4}"); do
-    statusCode=$(curl --insecure --silent --head "${2}" | awk '/^HTTP/{print $2}')
-    [[ $statusCode == "$3" ]] && return 0
-    sleep "${5}"
+  for attempt in $(seq 1 "${5}"); do
+    statusCode=$(curl --insecure --silent --head "${3}" | awk '/^HTTP/{print $2}')
+    [[ $statusCode == "$4" ]] && return 0
+    sleep "${6}"
   done
   return 1
 }
 
 # Pushes a directory onto the stack and asserts it succeeds
+#
+#   #1 = the name of the calling script
+#   #2 = the directory to push onto the stack
 function pushDir {
-  pushd "${1}" &>/dev/null || \
-    { logError "Failed to push $(sQuote "$(red "${1}")") onto directory stack." && exit 1 ; }
+  pushd "${2}" &>/dev/null || \
+    { logError "${1}" "Failed to push $(sQuote "$(red "${2}")") onto directory stack." && exit 1 ; }
 }
 
 # Pops a directory from the stack and asserts it succeeds
+#
+#   #1 = the name of the calling script
 function popDir {
-  popd &>/dev/null || { logError "Failed to pop from directory stack." && exit 1 ; }
+  popd &>/dev/null || { logError "${1}" "Failed to pop from directory stack." && exit 1 ; }
 }
 
 #    Naively formats a URL given: scheme, host, port & path components
diff --git a/ktor/serve b/ktor/serve
--- a/ktor/serve
+++ b/ktor/serve
@@ -4,9 +4,10 @@
     Serves HTML content using Ktor.
 '
 
+ME=$(basename "$0") && readonly ME
 source ../common
 
-function printUsageAndExit { logError "Usage: 'serve $(blue "CONFIG_FILE") $(blue "KEYSTORE_FILE")'"; exit 1; }
+function printUsageAndExit { logError "${ME}" "Usage: 'serve $(blue "CONFIG_FILE") $(blue "KEYSTORE_FILE")'"; exit 1; }
 
 # Check that we have exactly two arguments
 if [[ $# -ne 2 ]]; then printUsageAndExit; fi
@@ -16,7 +17,7 @@ CONFIG_FILE_PATH="${1}" && readonly CONFIG_FILE_PATH
 
 # Check that the specified configuration file exists
 if [[ ! -f $CONFIG_FILE_PATH ]]; then
-  logError "Configuration file $(sQuote "$(red "${CONFIG_FILE_PATH}")") inaccessible or nonexistent." \
+  logError "${ME}" "Configuration file $(sQuote "$(red "${CONFIG_FILE_PATH}")") inaccessible or nonexistent." \
     && printUsageAndExit
 fi
 
@@ -24,28 +25,28 @@ fi
 KEYSTORE_FILE_PATH="${2}" && readonly KEYSTORE_FILE_PATH
 # Check that the specified key store file exists
 if [[ ! -f $KEYSTORE_FILE_PATH ]]; then
-  logError "Key Store file $(sQuote "$(red "${KEYSTORE_FILE_PATH}")") inaccessible or nonexistent." && printUsageAndExit
+  logError "${ME}" "Key Store file $(sQuote "$(red "${KEYSTORE_FILE_PATH}")") inaccessible or nonexistent." && printUsageAndExit
 fi
 
 ERRORS=0
 # Ensure that Java is installed
-java -version &>/dev/null || { ERRORS=1 && logError "Java not found on the system." ; }
+java -version &>/dev/null || { ERRORS=1 && logError "${ME}" "Java not found on the system." ; }
 # Ensure that jq installed
-jq --version &>/dev/null || { ERRORS=1 && logError "$(sQuote "$(red "jq")") command not found." ; }
+jq --version &>/dev/null || { ERRORS=1 && logError "${ME}" "$(sQuote "$(red "jq")") command not found." ; }
 # If there's any error, exit
 if [ "$ERRORS" -ne "0" ]; then
-  logError "Exiting due to previous errors."; exit 1
+  logError "${ME}" "Exiting due to previous errors."; exit 1
 else
   # Read the configuration file's identity
   ID=$(jq -r '.id' "${CONFIG_FILE_PATH}") && readonly ID
   # Some initial user feedback
-  logInfo "Using the $(sQuote "$(blue "${ID}")") configuration."
+  logInfo "${ME}" "Using the $(sQuote "$(blue "${ID}")") configuration."
 
   # Read the JVM KeyStore path
-  logInfo "Using the JVM KeyStore at $(sQuote "$(blue "${KEYSTORE_FILE_PATH}")")."
+  logInfo "${ME}" "Using the JVM KeyStore at $(sQuote "$(blue "${KEYSTORE_FILE_PATH}")")."
 
   # Output the current Java version we will be using
-  java -version && logInfo "Press $(green "ctrl+d") to stop the server"
+  java -version && logInfo "${ME}" "Press $(green "ctrl+d") to stop the server"
 
   # Executing Ktor with Gradle
   ./gradlew --quiet run \
