Tests for image alt text.
- Updated to support edge, updated known good set of images to include edge screenshots
- Expanded the READMe.md
- Removed 'cd' output from clone_repository
- Added a CODE_OF_CONDUCT
- Added a CODEOWNERS
- Made the 'comp' script not create output directories if there's errors that will cause the script to fail
- Removed 'ie' from the valid browser target names
- Adding all Java System properties to interpolations
- Adding all Java Env. variables to interpolations
- Renamed browser.window.x(y) -> browser.x(y)
- Added Image class and ExternalImage class and added tests for image alt attribute values
- Split page concept into HostedPages and ExternalPages
- Changed the 'dateTime_formatter_pattern' to not include colons in the output
- Added 'gnome-terminal' as a checked dependency for the 'test' script
- Added constants for *_MAX_ATTEMPTS and *_POLLING_WAIT for 'test' script
- Added more details to the todo.md list ready for converting to GH issues

diff --git a/comp b/comp
--- a/comp
+++ b/comp
@@ -31,15 +31,6 @@ fi
 
 FORMAT="${3}" && readonly FORMAT
 
-OUT_DIR="${4}"
-readonly OUT_DIR
-if [ ! -d "${OUT_DIR}" ]; then
-  logInfo "Creating output directory $(sQuote "$(green "${OUT_DIR}")")"
-  if ! mkdir -p  "${OUT_DIR}"; then
-    ERRORS=1 && logError "Could not create output directory."
-  fi
-fi
-
 if [ "${DIR1}" == "${DIR2}" ]; then
   ERRORS=1 && logError "Both arguments point to the same directory $(sQuote "$(red "${DIR1}")")"
 fi
@@ -47,6 +38,18 @@ fi
 # Ensure that Image Magick is installed
 identify -version &>/dev/null \
   || { ERRORS=1 && logError "ImageMagick $(sQuote "$(blue "identify")") not found on the system."; }
+
+# Create the output directory if there's no errors up to this point
+OUT_DIR="${4}"
+readonly OUT_DIR
+if [ "$ERRORS" -eq "0" ]; then
+  if [ ! -d "${OUT_DIR}" ]; then
+    logInfo "Creating output directory $(sQuote "$(green "${OUT_DIR}")")"
+    if ! mkdir -p  "${OUT_DIR}"; then
+      ERRORS=1 && logError "Could not create output directory."
+    fi
+  fi
+fi
 
 # If there's any error, exit
 if [ "$ERRORS" -ne "0" ]; then
diff --git a/test b/test
--- a/test
+++ b/test
@@ -23,61 +23,85 @@ source common
 # Constants
 readonly KTOR_DIRECTORY="ktor"
 readonly SELENIUM_DIRECTORY="selenium"
+readonly KTOR_START_MAX_ATTEMPTS="20"
+readonly SELENIUM_START_MAX_ATTEMPTS="20"
+readonly SERVICE_POLLING_WAIT="1s"
 
 function printUsageAndExit { logError "Usage: 'test $(blue "CONFIG_FILE")'"; exit 1; }
 
 # Check that we have a single argument
 if [[ $# -ne 1 ]]; then printUsageAndExit; fi
 
-CONFIG_FILE="${1}" && readonly CONFIG_FILE
+ERRORS=0
+
+# Ensure that the gnome-terminal command is installed
+gnome-terminal --version &>/dev/null || \
+  { ERRORS=1 && logError "$(sQuote "$(red "gnome-terminal")") command not found." ; }
+
+# Ensure that jq installed
+jq --version &>/dev/null || { ERRORS=1 && logError "$(sQuote "$(red "jq")") command not found." ; }
 
 # Check that the provided configuration file argument value exists
+CONFIG_FILE="${1}" && readonly CONFIG_FILE
 if [[ ! -f $CONFIG_FILE ]]; then
-  logError "Configuration file $(sQuote "$(red "${CONFIG_FILE}")") inaccessible or nonexistent." && printUsageAndExit
+  ERRORS=1 && logError "Configuration file $(sQuote "$(red "${CONFIG_FILE}")") inaccessible or nonexistent."
 fi
+
+# If there's any error, print usage instructions and exit
+if [ "$ERRORS" -ne "0" ]; then printUsageAndExit ; fi
 
 # Read the configuration file's identity
 ID=$(jq -r '.id' "${CONFIG_FILE}") && readonly ID
+
 # Some initial user feedback
 logInfo "Executing test configuration $(sQuote "$(blue "${ID}")")."
 
-./clone_repository "${CONFIG_FILE}" || exit 1
+./clone_repository "${CONFIG_FILE}" || { logError "Failed to clone repository." && exit 1 ; }
 
 # Copy the Kotlin "Configuration" file from the root project to the ktor project
 logInfo "Copying the Kotlin configuration file $(sQuote "$(blue "src/test/kotlin/config/Configuration.kt")") to $(sQuote "$(green "servers/ktor/src/main/kotlin")")."
-cp -f src/test/kotlin/Configuration.kt "${KTOR_DIRECTORY}"/src/main/kotlin || {  logError "Failed to copy Configuration.kt file ." && exit 1 ; }
+cp -f src/test/kotlin/Configuration.kt "${KTOR_DIRECTORY}"/src/main/kotlin \
+  || {  logError "Failed to copy Configuration.kt file." && exit 1 ; }
 
-# Start Selenium
+### Start Selenium
 SELENIUM_SCHEME=$(jq -r ".tests.\"remote-web-driver\".\"scheme\"" "${CONFIG_FILE}") && readonly SELENIUM_SCHEME
-SELENIUM_BIND_ADDRESS=$(jq -r ".tests.\"remote-web-driver\".\"bind-address\"" "${CONFIG_FILE}") && readonly SELENIUM_BIND_ADDRESS
+SELENIUM_BIND_ADDRESS=$(jq -r ".tests.\"remote-web-driver\".\"bind-address\"" "${CONFIG_FILE}") && \
+  readonly SELENIUM_BIND_ADDRESS
 SELENIUM_PORT=$(jq -r ".tests.\"remote-web-driver\".port" "${CONFIG_FILE}") && readonly SELENIUM_PORT
-SELENIUM_URL=$(makeUrl "${SELENIUM_SCHEME}" "${SELENIUM_BIND_ADDRESS}" "${SELENIUM_PORT}" "/ui") && readonly SELENIUM_URL
+SELENIUM_URL=$(makeUrl "${SELENIUM_SCHEME}" "${SELENIUM_BIND_ADDRESS}" "${SELENIUM_PORT}" "/ui") && \
+readonly SELENIUM_URL
 readonly SELENIUM_STATUS_CODE=200
-if ! waitForStatusCode "Selenium" "${SELENIUM_URL}" "${SELENIUM_STATUS_CODE}" 1 1s; then
-  pushd "${SELENIUM_DIRECTORY}" &>/dev/null || { logError "Failed to push Ktor directory $(sQuote "$(red "${SELENIUM_DIRECTORY}")") onto directory stack." && exit 1 ; }
+if ! waitForStatusCode "Selenium" "${SELENIUM_URL}" "${SELENIUM_STATUS_CODE}" 1 "${SERVICE_POLLING_WAIT}" &>/dev/null ; then
+  pushd "${SELENIUM_DIRECTORY}" &>/dev/null || \
+    { logError "Failed to push Ktor directory \
+    $(sQuote "$(red "${SELENIUM_DIRECTORY}")") onto directory stack." && exit 1 ; }
   gnome-terminal -- bash -i -c "./serve ${CONFIG_FILE}; read"
   popd &>/dev/null || { logError "Failed to pop directory from stack." && exit 1 ; }
 fi
 
 # Start Ktor serving our branch
-KTOR_SCHEME=$(jq -r ".tests.\"remote-web-driver\".\"scheme\"" "${CONFIG_FILE}") && readonly KTOR_SCHEME
-KTOR_BIND_ADDRESS=$(jq -r ".tests.\"remote-web-driver\".\"bind-address\"" "${CONFIG_FILE}") && readonly KTOR_BIND_ADDRESS
-KTOR_PORT=$(jq -r ".tests.\"remote-web-driver\".port" "${CONFIG_FILE}") && readonly KTOR_PORT
-KTOR_URL=$(makeUrl "${KTOR_SCHEME}" "${KTOR_BIND_ADDRESS}" "${KTOR_PORT}" "/0386fc26-b323-4eb7-8cb8-840495c363d0") && readonly KTOR_URL
+KTOR_SCHEME=$(jq -r ".serving.scheme" "${CONFIG_FILE}") && readonly KTOR_SCHEME
+KTOR_BIND_ADDRESS=$(jq -r ".serving.\"bind-address\"" "${CONFIG_FILE}") && readonly KTOR_BIND_ADDRESS
+KTOR_PORT=$(jq -r ".serving.port" "${CONFIG_FILE}") && readonly KTOR_PORT
+KTOR_URL=$(makeUrl "${KTOR_SCHEME}" "${KTOR_BIND_ADDRESS}" "${KTOR_PORT}" "/0386fc26-b323-4eb7-8cb8-840495c363d0") && \
+  readonly KTOR_URL
 readonly KTOR_STATUS_CODE=404
-if ! waitForStatusCode "Ktor" "${KTOR_URL}" "${KTOR_STATUS_CODE}" 1 1s; then
-  pushd "${KTOR_DIRECTORY}" &>/dev/null || { logError "Failed to push Ktor directory $(sQuote "$(red "${KTOR_DIRECTORY}")") onto directory stack." && exit 1 ; }
+if ! waitForStatusCode "Ktor" "${KTOR_URL}" "${KTOR_STATUS_CODE}" 1 "${SERVICE_POLLING_WAIT}" &>/dev/null; then
+  pushd "${KTOR_DIRECTORY}" &>/dev/null || { logError \
+    "Failed to push Ktor directory $(sQuote "$(red "${KTOR_DIRECTORY}")") onto directory stack." && exit 1 ; }
   gnome-terminal -- bash -i -c "./serve ${CONFIG_FILE}; read"
   popd &>/dev/null || { logError "Failed to pop directory from stack." && exit 1 ; }
 fi
 
 # Wait for a 404 status code from requesting a non existent page from Ktor
-waitForStatusCode "Ktor" "${KTOR_URL}" "${KTOR_STATUS_CODE}" 20 1s  || { logError "Failure in bringing up Ktor server." && exit 1 ; }
+waitForStatusCode "Ktor" "${KTOR_URL}" "${KTOR_STATUS_CODE}" ${KTOR_START_MAX_ATTEMPTS} "${SERVICE_POLLING_WAIT}" \
+  || { logError "Failure in bringing up Ktor server." && exit 1 ; }
 logInfo "Ktor is ready."
 
 # Wait for a 200 status code from Selenium
-waitForStatusCode "Selenium" "${SELENIUM_URL}" "${SELENIUM_STATUS_CODE}" 20 1s || { logError "Failure in bringing up Selenium standalone server." && exit 1 ; }
+waitForStatusCode "Selenium" "${SELENIUM_URL}" "${SELENIUM_STATUS_CODE}" ${SELENIUM_START_MAX_ATTEMPTS} \
+  "${SERVICE_POLLING_WAIT}" || { logError "Failure in bringing up Selenium standalone server." && exit 1 ; }
 logInfo "Selenium is ready."
 
-## Run the Selenium tests
+# Run the Selenium tests
 ./gradlew test -Dio.github.learnyouahaskell.test.config="${CONFIG_FILE}"
